name: Integration Tests with Supabase

on:
  pull_request:
    branches:
      - main
    paths: &watched_paths
      - 'config/**'
      - 'assets/**'
      - 'lib/**'
      - 'priv/**'
      - 'mix.exs'
      - 'mix.lock'
      - 'Dockerfile'
      - 'run.sh'
      - 'test/e2e/supabase/**'
      - '.github/workflows/integration-supabase.yml'
  push:
    branches:
      - main
    paths: *watched_paths

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: test/e2e/supabase

jobs:
  test:
    name: Playwright Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browsers:
          - name: Chrome
            project: chromium
          - name: Firefox
            project: firefox
          - name: Safari
            project: webkit

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and cache Logflare image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: supabase/logflare:local
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        pull: true

    - name: Move Docker cache
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      working-directory: .

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
        cache-dependency-path: test/e2e/supabase/package-lock.json

    - name: Setup Supabase services
      run: bash ./setup-supabase-services.sh

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright ${{ matrix.browsers.name }} Browser
      run: npx playwright install ${{ matrix.browsers.project }} --with-deps

    - name: Run Playwright tests (only ${{ matrix.browsers.name }})
      run: npx playwright test --project ${{ matrix.browsers.project }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
